services:
    app:
        build: .
        environment:
            - PG_HOST=${PG_HOST}
            - PG_PASSWORD=${PG_PASSWORD}
            - DISCORD_TOKEN=${DISCORD_TOKEN}
            
            