name: Deploy to Portainer

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        ls
        docker build -t discord-bait:latest .

    - name: Push Docker image to Portainer
      env:
        PORTAINER_URL: ${{ secrets.PORTAINER_URL }}
        PORTAINER_API_KEY: ${{ secrets.PORTAINER_API_KEY }}
      run: |
        docker tag discord-bait:latest ${{ secrets.PORTAINER_URL }}/discord-bait:latest
        docker push ${{ secrets.PORTAINER_URL }}/discord-bait:latest

    - name: Deploy to Portainer
      env:
        PORTAINER_URL: ${{ secrets.PORTAINER_URL }}
        PORTAINER_API_KEY: ${{ secrets.PORTAINER_API_KEY }}
      run: |
        curl -X POST "$PORTAINER_URL/api/endpoints/2/docker/containers/discord-bait/update" \
          -H "X-API-Key:$PORTAINER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{"image": "${{ secrets.PORTAINER_URL }}/discord-bait:latest"}'
